# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import myproto_pb2 as myproto__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in myproto_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class AggregatorStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SendSharedUpdate = channel.unary_unary(
                '/fedavg.Aggregator/SendSharedUpdate',
                request_serializer=myproto__pb2.SharedUpdate.SerializeToString,
                response_deserializer=myproto__pb2.Ack.FromString,
                _registered_method=True)
        self.GetSharedWeights = channel.unary_unary(
                '/fedavg.Aggregator/GetSharedWeights',
                request_serializer=myproto__pb2.EmptyRequest.SerializeToString,
                response_deserializer=myproto__pb2.SharedWeights.FromString,
                _registered_method=True)


class AggregatorServicer(object):
    """Missing associated documentation comment in .proto file."""

    def SendSharedUpdate(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSharedWeights(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AggregatorServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SendSharedUpdate': grpc.unary_unary_rpc_method_handler(
                    servicer.SendSharedUpdate,
                    request_deserializer=myproto__pb2.SharedUpdate.FromString,
                    response_serializer=myproto__pb2.Ack.SerializeToString,
            ),
            'GetSharedWeights': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSharedWeights,
                    request_deserializer=myproto__pb2.EmptyRequest.FromString,
                    response_serializer=myproto__pb2.SharedWeights.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'fedavg.Aggregator', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('fedavg.Aggregator', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Aggregator(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SendSharedUpdate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/fedavg.Aggregator/SendSharedUpdate',
            myproto__pb2.SharedUpdate.SerializeToString,
            myproto__pb2.Ack.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetSharedWeights(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/fedavg.Aggregator/GetSharedWeights',
            myproto__pb2.EmptyRequest.SerializeToString,
            myproto__pb2.SharedWeights.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
